# Generated by Django 5.2 on 2025-05-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gparecord',
            options={'ordering': ['student', 'semester']},
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='creator',
            field=models.CharField(choices=[('Ijlal', 'Ijlal'), ('Dadia', 'Dadia'), ('Shynny', 'Shynny'), ('Amel', 'Amel')], default='Ijlal', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='gparecord',
            unique_together={('student', 'semester')},
        ),
    ]
