# Generated by Django 5.2 on 2025-05-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0002_alter_gparecord_options_alter_mlmodel_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='r2_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='rmse',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('linear_regression', 'Linear Regression'), ('clustering', 'Clustering')], max_length=20),
        ),
    ]
