# Generated by Django 5.2.1 on 2025-05-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0003_mlmodel_r2_score_mlmodel_rmse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='r2_score',
        ),
        migrations.RemoveField(
            model_name='mlmodel',
            name='rmse',
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='dataset',
            field=models.FileField(upload_to='datasets/'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('clustering', 'Clustering')], max_length=20),
        ),
    ]
